### ISSUE TITLE
Files in retry folder get executed multiple times 

### ISSUE THREAD

**Issue by akumar03** [informatics-isi-edu/iobox-win32#18] opened 2016-06-03 01:10 UTC
When we saved files from hatrac and ermrest failure to retry folder, we observed that in certain instances ermrest calls were successful but not hatrac.  Found more records in ermrest than hatrac. If the flow works properly it should never happen.

**Comment by carlkesselman** [comment] 2016-06-03 01:33
Is this repeatable?  Can we generate a test case that causes this to happen?

Carl

---

Dr. Carl Kesselman
Dean’s Professor, Epstein Department of Industrial and Systems Engineering
Fellow, Information Sciences Institute
Viterbi School of Engineering

Professor, Preventive Medicine
Keck School of Medicine

University of Southern California
4676 Admiralty Way, Suite 1001, Marina del Rey, CA  90292-6695
Phone:  +1 (310) 448-9338
Email:  carl@isi.edumailto:carl@isi.edu
Web: http://www.isi.edu/~carl

On Jun 2, 2016, at 6:10 PM, akumar03 <notifications@github.com<mailto:notifications@github.com>> wrote:

When we saved files from hatrac and ermrest failure to retry folder, we observed that in certain instances ermrest calls were successful but not hatrac. Found more records in ermrest than hatrac. If the flow works properly it should never happen.

**Comment by carlkesselman** [comment] 2016-06-03 01:34
Lets look at the hatrac log for errors.

Carl

---

Dr. Carl Kesselman
Dean’s Professor, Epstein Department of Industrial and Systems Engineering
Fellow, Information Sciences Institute
Viterbi School of Engineering

Professor, Preventive Medicine
Keck School of Medicine

University of Southern California
4676 Admiralty Way, Suite 1001, Marina del Rey, CA  90292-6695
Phone:  +1 (310) 448-9338
Email:  carl@isi.edumailto:carl@isi.edu
Web: http://www.isi.edu/~carl

On Jun 2, 2016, at 6:33 PM, Carl Kesselman <carl@exchange.isi.edu<mailto:carl@exchange.isi.edu>> wrote:

Is this repeatable?  Can we generate a test case that causes this to happen?

Carl

---

Dr. Carl Kesselman
Dean’s Professor, Epstein Department of Industrial and Systems Engineering
Fellow, Information Sciences Institute
Viterbi School of Engineering

Professor, Preventive Medicine
Keck School of Medicine

University of Southern California
4676 Admiralty Way, Suite 1001, Marina del Rey, CA  90292-6695
Phone:  +1 (310) 448-9338
Email:  carl@isi.edumailto:carl@isi.edu
Web: http://www.isi.edu/~carl

On Jun 2, 2016, at 6:10 PM, akumar03 <notifications@github.com<mailto:notifications@github.com>> wrote:

When we saved files from hatrac and ermrest failure to retry folder, we observed that in certain instances ermrest calls were successful but not hatrac. Found more records in ermrest than hatrac. If the flow works properly it should never happen.

**Comment by carlkesselman** [comment] 2016-06-03 02:26
So let me follow up an be more specific:

1) We need to know why hatrac failed.  We should look in the log file for IOBox and Hatrac.  If this is not recorded in the logs, then this needs to be fixed.  It is not good enough just to fix the bug, we need to understand the cause.  There are valid reasons why hatrac might fail, and also invalid reasons.  We should determine which this is or else we may be missing fixing a potential future problem before it happens.
2) There seems to be an issue with the retry, this needs to be fixed.
3) I think in general, it would be useful to provide more details in a bug report such as this.  Upload the log files, or excerpts, provide details of how to reproduce, etc.  Think about what you would need to know if you were to debug this.

Thanks,

Carl

---

Dr. Carl Kesselman
Dean’s Professor, Epstein Department of Industrial and Systems Engineering
Fellow, Information Sciences Institute
Viterbi School of Engineering

Professor, Preventive Medicine
Keck School of Medicine

University of Southern California
4676 Admiralty Way, Suite 1001, Marina del Rey, CA  90292-6695
Phone:  +1 (310) 448-9338
Email:  carl@isi.edumailto:carl@isi.edu
Web: http://www.isi.edu/~carl

On Jun 2, 2016, at 6:34 PM, Carl Kesselman <carl@isi.edu<mailto:carl@isi.edu>> wrote:

Lets look at the hatrac log for errors.

Carl

---

Dr. Carl Kesselman
Dean’s Professor, Epstein Department of Industrial and Systems Engineering
Fellow, Information Sciences Institute
Viterbi School of Engineering

Professor, Preventive Medicine
Keck School of Medicine

University of Southern California
4676 Admiralty Way, Suite 1001, Marina del Rey, CA  90292-6695
Phone:  +1 (310) 448-9338
Email:  carl@isi.edumailto:carl@isi.edu
Web: http://www.isi.edu/~carl

On Jun 2, 2016, at 6:33 PM, Carl Kesselman <carl@exchange.isi.edu<mailto:carl@exchange.isi.edu>> wrote:

Is this repeatable?  Can we generate a test case that causes this to happen?

Carl

---

Dr. Carl Kesselman
Dean’s Professor, Epstein Department of Industrial and Systems Engineering
Fellow, Information Sciences Institute
Viterbi School of Engineering

Professor, Preventive Medicine
Keck School of Medicine

University of Southern California
4676 Admiralty Way, Suite 1001, Marina del Rey, CA  90292-6695
Phone:  +1 (310) 448-9338
Email:  carl@isi.edumailto:carl@isi.edu
Web: http://www.isi.edu/~carl

On Jun 2, 2016, at 6:10 PM, akumar03 <notifications@github.com<mailto:notifications@github.com>> wrote:

When we saved files from hatrac and ermrest failure to retry folder, we observed that in certain instances ermrest calls were successful but not hatrac. Found more records in ermrest than hatrac. If the flow works properly it should never happen.

**Comment by akumar03** [comment] 2016-06-03 13:35
This happened when Jeff uploaded ~2700 fcs files.  We haven't observed the behavior on individual files.   We spoke to @svoinea about the problem and he said he will review the code that hanldes retries.

**Comment by carlkesselman** [comment] 2016-06-03 14:31
Ok,

But there still is the issue as to why the files didn’t transfer to hatrac in the first place. Do the logs tell us what happened?

So for the files that didn’t get transferred, they were in the retry directory?

Carl

---

Dr. Carl Kesselman
Dean’s Professor, Epstein Department of Industrial and Systems Engineering
Fellow, Information Sciences Institute
Viterbi School of Engineering

Professor, Preventive Medicine
Keck School of Medicine

University of Southern California
4676 Admiralty Way, Suite 1001, Marina del Rey, CA  90292-6695
Phone:  +1 (310) 448-9338
Email:  carl@isi.edumailto:carl@isi.edu
Web: http://www.isi.edu/~carl

On Jun 3, 2016, at 6:35 AM, akumar03 <notifications@github.com<mailto:notifications@github.com>> wrote:

This happened when Jeff uploaded ~2700 fcs files. We haven't observed the behavior on individual files. We spoke to @svoineahttps://github.com/svoinea about the problem and he said he will review the code that hanldes retries.

**Comment by carlkesselman** [comment] 2016-06-04 19:23
So to be explicit: can we post the parts of the hatrac and IOBox log files that indicate the transfer failure.

I really do want to determine if there is a systematic issue with the transfer, or if it was a transient, what was the cause.  This information should be in the logs, if it isn’t we must fix it.  If it is, then we should be able to easily find it.

Also, can we confirm or deny that Jeff got an email notification on the failure.  This needs a yes or no answer.  If the answer is no, then we must fix and text this feature.

It is not acceptable to get silent failures without us knowing that this happened.

Thanks,

Carl

---

Dr. Carl Kesselman
Dean’s Professor, Epstein Department of Industrial and Systems Engineering
Fellow, Information Sciences Institute
Viterbi School of Engineering

Professor, Preventive Medicine
Keck School of Medicine

University of Southern California
4676 Admiralty Way, Suite 1001, Marina del Rey, CA  90292-6695
Phone:  +1 (310) 448-9338
Email:  carl@isi.edumailto:carl@isi.edu
Web: http://www.isi.edu/~carl

On Jun 3, 2016, at 7:31 AM, Carl Kesselman <carl@isi.edu<mailto:carl@isi.edu>> wrote:

Ok,

But there still is the issue as to why the files didn’t transfer to hatrac in the first place. Do the logs tell us what happened?

So for the files that didn’t get transferred, they were in the retry directory?

Carl

---

Dr. Carl Kesselman
Dean’s Professor, Epstein Department of Industrial and Systems Engineering
Fellow, Information Sciences Institute
Viterbi School of Engineering

Professor, Preventive Medicine
Keck School of Medicine

University of Southern California
4676 Admiralty Way, Suite 1001, Marina del Rey, CA  90292-6695
Phone:  +1 (310) 448-9338
Email:  carl@isi.edumailto:carl@isi.edu
Web: http://www.isi.edu/~carl

On Jun 3, 2016, at 6:35 AM, akumar03 <notifications@github.com<mailto:notifications@github.com>> wrote:

This happened when Jeff uploaded ~2700 fcs files. We haven't observed the behavior on individual files. We spoke to @svoineahttps://github.com/svoinea about the problem and he said he will review the code that hanldes retries.

**Comment by karlcz** [comment] 2016-06-07 18:27
Also please give more specifics about the workload.  ~2700 files with what sizes?  Over what kind of network path (local California or trans-Pacific)? Is there anything different about the failed files, e.g. larger or smaller?  Or perhaps time of day differences?

I can easily see that file upload will be more sensitive to network errors and timeouts than the metadata updates, and this would likely be something to address by tuning the chunked upload chunk size and retry behaviors (perhaps via runtime config options if certain deployments need really extreme settings due to network characteristics).

**Comment by akumar03** [comment] 2016-06-08 01:54
Reviewed the iobox  logs and we couldn't find checksums for these files. Also wanted to clarify that the problem is other way around. We have entries in hatrac but not ermrest.  We have 2728 entries in hatrac and 2722 in ermrest.  These errors only happened on May 27th and none after that.  We had opposite problem with earlier run. We will keep watching this issue.

**Comment by hongsudt** [comment] 2016-07-06 01:37
@akumar03 @svoinea is this still an issue?

**Comment by svoinea** [comment] 2016-07-08 17:00
Problem is fixed at this time.
Assigning to @akumar03 for review.

**Closed as completed** 2016-07-17 14:48 UTC
