### ISSUE TITLE
Support Ermrest get protocol

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/iobox-win32#8] opened 2016-05-04 22:52 UTC
So that I can retrieve the entity metadata and assign them to variables to be used later.

**Comment by svoinea** [comment] 2016-06-30 16:06
Done in commit e47182de4a462bdde37217f029a176789bbbb3a3

**Comment by svoinea** [comment] 2016-07-01 16:17
This is a duplicate of #22

**Closed as completed by svoinea** 2016-07-01 16:17 UTC
